USE [master]
GO
/****** Object:  Database [Turkcell]    Script Date: 22.04.2023 22:20:49 ******/
CREATE DATABASE [Turkcell]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Turkcell', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Turkcell.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Turkcell_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Turkcell_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Turkcell] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Turkcell].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Turkcell] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Turkcell] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Turkcell] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Turkcell] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Turkcell] SET ARITHABORT OFF 
GO
ALTER DATABASE [Turkcell] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Turkcell] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Turkcell] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Turkcell] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Turkcell] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Turkcell] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Turkcell] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Turkcell] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Turkcell] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Turkcell] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Turkcell] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Turkcell] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Turkcell] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Turkcell] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Turkcell] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Turkcell] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Turkcell] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Turkcell] SET RECOVERY FULL 
GO
ALTER DATABASE [Turkcell] SET  MULTI_USER 
GO
ALTER DATABASE [Turkcell] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Turkcell] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Turkcell] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Turkcell] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Turkcell] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Turkcell] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Turkcell', N'ON'
GO
ALTER DATABASE [Turkcell] SET QUERY_STORE = ON
GO
ALTER DATABASE [Turkcell] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Turkcell]
GO
/****** Object:  Table [dbo].[BuyPrices]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BuyPrices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Waste] [int] NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_BuyPrices] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Collectors]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Collectors](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[Phone] [varchar](11) NOT NULL,
 CONSTRAINT [PK_Collectors] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Companys]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Companys](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[TaxNumber] [varchar](50) NOT NULL,
	[Phone] [varchar](11) NOT NULL,
 CONSTRAINT [PK_Companys] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[Phone] [varchar](11) NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Entries]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Entries](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Employee] [int] NOT NULL,
	[Collector] [int] NOT NULL,
	[Quantity] [float] NOT NULL,
	[Waste] [int] NOT NULL,
	[Price] [int] NOT NULL,
	[Amount] [float] NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Entries] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Outputs]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Outputs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Employee] [int] NOT NULL,
	[Company] [int] NOT NULL,
	[Quantity] [float] NOT NULL,
	[Waste] [int] NOT NULL,
	[Price] [int] NOT NULL,
	[Amount] [float] NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Outputs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SellPrices]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SellPrices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Waste] [int] NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_SellPrices] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stocks]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stocks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Waste] [int] NOT NULL,
	[Stock] [float] NOT NULL,
 CONSTRAINT [PK_Stocks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Wastes]    Script Date: 22.04.2023 22:20:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Wastes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Wastes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BuyPrices]  WITH CHECK ADD  CONSTRAINT [FK_BuyPrices_Wastes] FOREIGN KEY([Waste])
REFERENCES [dbo].[Wastes] ([Id])
GO
ALTER TABLE [dbo].[BuyPrices] CHECK CONSTRAINT [FK_BuyPrices_Wastes]
GO
ALTER TABLE [dbo].[Entries]  WITH CHECK ADD  CONSTRAINT [FK_Entries_BuyPrices] FOREIGN KEY([Price])
REFERENCES [dbo].[BuyPrices] ([Id])
GO
ALTER TABLE [dbo].[Entries] CHECK CONSTRAINT [FK_Entries_BuyPrices]
GO
ALTER TABLE [dbo].[Entries]  WITH CHECK ADD  CONSTRAINT [FK_Entries_Collectors] FOREIGN KEY([Collector])
REFERENCES [dbo].[Collectors] ([Id])
GO
ALTER TABLE [dbo].[Entries] CHECK CONSTRAINT [FK_Entries_Collectors]
GO
ALTER TABLE [dbo].[Entries]  WITH CHECK ADD  CONSTRAINT [FK_Entries_Employees] FOREIGN KEY([Employee])
REFERENCES [dbo].[Employees] ([Id])
GO
ALTER TABLE [dbo].[Entries] CHECK CONSTRAINT [FK_Entries_Employees]
GO
ALTER TABLE [dbo].[Entries]  WITH CHECK ADD  CONSTRAINT [FK_Entries_Wastes] FOREIGN KEY([Waste])
REFERENCES [dbo].[Wastes] ([Id])
GO
ALTER TABLE [dbo].[Entries] CHECK CONSTRAINT [FK_Entries_Wastes]
GO
ALTER TABLE [dbo].[Outputs]  WITH CHECK ADD  CONSTRAINT [FK_Outputs_Companys] FOREIGN KEY([Company])
REFERENCES [dbo].[Companys] ([Id])
GO
ALTER TABLE [dbo].[Outputs] CHECK CONSTRAINT [FK_Outputs_Companys]
GO
ALTER TABLE [dbo].[Outputs]  WITH CHECK ADD  CONSTRAINT [FK_Outputs_Employees] FOREIGN KEY([Employee])
REFERENCES [dbo].[Employees] ([Id])
GO
ALTER TABLE [dbo].[Outputs] CHECK CONSTRAINT [FK_Outputs_Employees]
GO
ALTER TABLE [dbo].[Outputs]  WITH CHECK ADD  CONSTRAINT [FK_Outputs_SellPrices] FOREIGN KEY([Price])
REFERENCES [dbo].[SellPrices] ([Id])
GO
ALTER TABLE [dbo].[Outputs] CHECK CONSTRAINT [FK_Outputs_SellPrices]
GO
ALTER TABLE [dbo].[Outputs]  WITH CHECK ADD  CONSTRAINT [FK_Outputs_Wastes] FOREIGN KEY([Waste])
REFERENCES [dbo].[Wastes] ([Id])
GO
ALTER TABLE [dbo].[Outputs] CHECK CONSTRAINT [FK_Outputs_Wastes]
GO
ALTER TABLE [dbo].[SellPrices]  WITH CHECK ADD  CONSTRAINT [FK_SellPrices_Wastes] FOREIGN KEY([Waste])
REFERENCES [dbo].[Wastes] ([Id])
GO
ALTER TABLE [dbo].[SellPrices] CHECK CONSTRAINT [FK_SellPrices_Wastes]
GO
ALTER TABLE [dbo].[Stocks]  WITH CHECK ADD  CONSTRAINT [FK_Stocks_Wastes] FOREIGN KEY([Waste])
REFERENCES [dbo].[Wastes] ([Id])
GO
ALTER TABLE [dbo].[Stocks] CHECK CONSTRAINT [FK_Stocks_Wastes]
GO
USE [master]
GO
ALTER DATABASE [Turkcell] SET  READ_WRITE 
GO
